config/routes.rb
Rails.application.routes.draw do
  resources :projet_themes
  resources :projet_forms
  resources :projet_targets
  resources :projets
  resources :forms
  resources :themes
  resources :targets
  devise_for :users
  get "home", to: "pages#home"
  get "quizz", to: "pages#quizz"
  get "about", to: "pages#about"
  get "mention", to: "pages#mention"
  get "update", to: "pages#update"
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/projet.rb
class Projet < ApplicationRecord
    has_many :projet_target, dependent: :destroy
    has_many :projet_theme, dependent: :destroy
    has_many :projet_form, dependent: :destroy
    has_many :theme, through: :projet_theme
    has_many :target, through: :projet_target
    has_many :form, through: :projet_form
    has_one_attached :photo


    def show_target
        if self.target.count > 1
            data = 'a partir de' + self.target.first.name
        else
            data = '--'
            data = self.target.first.name if self.target.first
        end
        data
    end

    def show_text
        data = self.synopsis
        if self.stars_text
            data = self.stars_text if (self.stars_text != "" && self.stars_text != " ")
        end
        data
        
    end
end

app/models/projet_form.rb
class ProjetForm < ApplicationRecord
  belongs_to :projet
  belongs_to :form
end

app/controllers/projets_controller.rb
class ProjetsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_projet, only: [:show, :edit, :update, :destroy]

  # GET /projets
  # GET /projets.json
  def index
    @projets = Projet.all
  end

  # GET /projets/1
  # GET /projets/1.json
  def show
  end

  # GET /projets/new
  def new
    @projet = Projet.new
    redirect_to request.referrer
  end

  # GET /projets/1/edit
  def edit
    redirect_to request.referrer
  end

  # POST /projets
  # POST /projets.json
  def create
    @projet = Projet.new(projet_params)

    if params[:target]
      ProjetTarget.where({projet: @projet}).destroy_all
      ProjetTarget.create!({projet: @projet, target: Target.find(params[:target]) }) if ProjetTarget.where(projet: @projet, target: Target.find(params[:target]) ).count == 0
    end


    if params[:more_form]
      params[:more_form].split(';').each do |id|
        form = Form.find(id)
      
        ProjetForm.create!({projet: @projet, form: form }) if ProjetForm.where(projet: @projet, form:form).count == 0
      end
    end

    if params[:less_form]
      params[:less_form].split(';').each do |id|
        ProjetForm.where(projet: @projet, form: Form.find(id))[0].destroy! if ProjetForm.where(projet: @projet, form: Form.find(id))[0]
      end
    end

    if params[:more_theme]
      params[:more_theme].split(';').each do |id|
        theme = Theme.find(id)
      
        ProjetTheme.create!({projet: @projet, theme: theme }) if ProjetTheme.where(projet: @projet, theme:theme).count == 0
      end
    end

    if params[:less_theme]
      params[:less_theme].split(';').each do |id|
        ProjetTheme.where(projet: @projet, theme: Theme.find(id))[0].destroy! if ProjetTheme.where(projet: @projet, theme: Theme.find(id))[0]
      end
    end

    redirect_to request.referrer

    
    
  end

  # PATCH/PUT /projets/1
  # PATCH/PUT /projets/1.json
  def update
    
 
       @projet.update!(projet_params)

        if params[:more_form]
          params[:more_form].split(';').each do |id|
            form = Form.find(id)
          
            ProjetForm.create!({projet: @projet, form: form }) if ProjetForm.where(projet: @projet, form:form).count == 0
          end
        end

        if params[:less_form]
          params[:less_form].split(';').each do |id|
            ProjetForm.where(projet: @projet, form: Form.find(id))[0].destroy! if ProjetForm.where(projet: @projet, form: Form.find(id))[0]
          end
        end

        if params[:target]
          ProjetTarget.where({projet: @projet}).destroy_all
          ProjetTarget.create!({projet: @projet, target: Target.find(params[:target]) }) if ProjetTarget.where(projet: @projet, target: Target.find(params[:target]) ).count == 0
        end

        if params[:more_theme]
          params[:more_theme].split(';').each do |id|
            theme = Theme.find(id)
          
            ProjetTheme.create!({projet: @projet, theme: theme }) if ProjetTheme.where(projet: @projet, theme:theme).count == 0
          end
        end

        if params[:less_theme]
          params[:less_theme].split(';').each do |id|
            ProjetTheme.where(projet: @projet, theme: Theme.find(id))[0].destroy! if ProjetTheme.where(projet: @projet, theme: Theme.find(id))[0]
          end
        end
       # format.html { redirect_to @projet, notice: 'Projet was successfully updated.' }
        #format.json { render :show, status: :ok, location: @projet }
        
        redirect_to request.referrer
      
       

    
  end

  # DELETE /projets/1
  # DELETE /projets/1.json
  def destroy
    @projet.destroy
    respond_to do |format|
      format.html { redirect_to request.referrer, notice: 'Projet supprimé' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projet
      @projet = Projet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def projet_params
      params.require(:projet).permit(:name_structure, :title, :url, :keywords, :difficulty, :date, :live, :synopsis, :image, :territory, :duration, :stars, :stars_text, :double, :question, :good_answer, :prop_1, :prop_2, :answer, :double, :photo)
    end
end

app/views/projets/_form.html.erb
<%= simple_form_for(@projet) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name_structure %>
    <%= f.input :title %>
    <%= f.input :url %>
    <%= f.input :keywords %>
    <%= f.input :difficulty %>
    <%= f.input :date %>
    <%= f.input :live %>
    <%= f.input :synopsis %>
    <%= f.input :image %>
    <%= f.input :territory %>
    <%= f.input :duration %>
    <%= f.input :stars %>
    <%= f.input :double %>
    <%= f.input :question %>
    <%= f.input :stars_text %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/projets/edit.html.erb
<h1>Editing Projet</h1>

<%= render 'form', projet: @projet %>

<%= link_to 'Show', @projet %> |
<%= link_to 'Back', projets_path %>

app/views/projets/index.html.erb
<div class="container mt-5">
<p id="notice"><%= notice %></p>

<h1>Projets</h1>

<table>
  <thead>
    <tr>
      <th>Name structure</th>
      <th>Title</th>
      <th>Url</th>
      <th>Keywords</th>
      <th>Difficulty</th>
      <th>Date</th>
      <th>Live</th>
      <th>Synopsis</th>
      <th>Image</th>
      <th>Territory</th>
      <th>Duration</th>
      <th>Stars</th>
      <th>Double</th>
      <th>Stars text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projets.each do |projet| %>
      <tr>
        <td><%= projet.name_structure %></td>
        <td><%= projet.title.first(30) %></td>
        <td><%= projet.url %></td>
        <td><%= projet.keywords.first(30) if projet.keywords %></td>
        <td><%= projet.difficulty %></td>
        <td><%= projet.date %></td>
        <td><%= projet.live %></td>
        <td><%= projet.synopsis.first(30)%></td>
        <td><%= projet.image %></td>
        <td><%= projet.territory %></td>
        <td><%= projet.duration %></td>
        <td><%= projet.stars %></td>
        <td><%= projet.double %></td>
        <td><%= projet.stars_text %></td>
        <td><%= link_to 'Show', projet %></td>
        <td><%= link_to 'Edit', edit_projet_path(projet) %></td>
        <td><%= link_to 'Destroy', projet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Projet', new_projet_path %>
</div>

app/views/projets/new.html.erb
<h1>New Projet</h1>

<%= render 'form', projet: @projet %>

<%= link_to 'Back', projets_path %>

app/views/projets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name structure:</strong>
  <%= @projet.name_structure %>
</p>

<p>
  <strong>Title:</strong>
  <%= @projet.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @projet.url %>
</p>

<p>
  <strong>Keywords:</strong>
  <%= @projet.keywords %>
</p>

<p>
  <strong>Difficulty:</strong>
  <%= @projet.difficulty %>
</p>

<p>
  <strong>Date:</strong>
  <%= @projet.date %>
</p>

<p>
  <strong>Live:</strong>
  <%= @projet.live %>
</p>

<p>
  <strong>Synopsis:</strong>
  <%= @projet.synopsis %>
</p>

<p>
  <strong>Image:</strong>
  <%= @projet.image %>
</p>

<p>
  <strong>Territory:</strong>
  <%= @projet.territory %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @projet.duration %>
</p>

<p>
  <strong>Stars:</strong>
  <%= @projet.stars %>
</p>

<p>
  <strong>Double:</strong>
  <%= @projet.double %>
</p>

<p>
  <strong>Stars text:</strong>
  <%= @projet.stars_text %>
</p>

<%= link_to 'Edit', edit_projet_path(@projet) %> |
<%= link_to 'Back', projets_path %>