config/routes.rb
Rails.application.routes.draw do
  resources :projet_themes
  resources :projet_forms
  resources :projet_targets
  resources :projets
  resources :forms
  resources :themes
  resources :targets
  devise_for :users
  get "home", to: "pages#home"
  get "quizz", to: "pages#quizz"
  get "about", to: "pages#about"
  get "mention", to: "pages#mention"
  get "update", to: "pages#update"
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/projet_forms_controller.rb
class ProjetFormsController < ApplicationController
  before_action :set_projet_form, only: [:show, :edit, :update, :destroy]

  # GET /projet_forms
  # GET /projet_forms.json
  def index
    @projet_forms = ProjetForm.all
  end

  # GET /projet_forms/1
  # GET /projet_forms/1.json
  def show
  end

  # GET /projet_forms/new
  def new
    @projet_form = ProjetForm.new
  end

  # GET /projet_forms/1/edit
  def edit
  end

  # POST /projet_forms
  # POST /projet_forms.json
  def create
    @projet_form = ProjetForm.new(projet_form_params)

    respond_to do |format|
      if @projet_form.save
        format.html { redirect_to @projet_form, notice: 'Projet form was successfully created.' }
        format.json { render :show, status: :created, location: @projet_form }
      else
        format.html { render :new }
        format.json { render json: @projet_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projet_forms/1
  # PATCH/PUT /projet_forms/1.json
  def update
    respond_to do |format|
      if @projet_form.update(projet_form_params)
        format.html { redirect_to @projet_form, notice: 'Projet form was successfully updated.' }
        format.json { render :show, status: :ok, location: @projet_form }
      else
        format.html { render :edit }
        format.json { render json: @projet_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projet_forms/1
  # DELETE /projet_forms/1.json
  def destroy
    @projet_form.destroy
    respond_to do |format|
      format.html { redirect_to projet_forms_url, notice: 'Projet form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projet_form
      @projet_form = ProjetForm.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def projet_form_params
      params.require(:projet_form).permit(:projet_id, :form_id)
    end
end

app/views/projet_forms/_form.html.erb
<%= simple_form_for(@projet_form) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :projet %>
    <%= f.association :form %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/projet_forms/edit.html.erb
<h1>Editing Projet Form</h1>

<%= render 'form', projet_form: @projet_form %>

<%= link_to 'Show', @projet_form %> |
<%= link_to 'Back', projet_forms_path %>

app/views/projet_forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projet Forms</h1>

<table>
  <thead>
    <tr>
      <th>Projet</th>
      <th>Form</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projet_forms.each do |projet_form| %>
      <tr>
        <td><%= projet_form.projet_id %></td>
        <td><%= projet_form.form_id %></td>
        <td><%= link_to 'Show', projet_form %></td>
        <td><%= link_to 'Edit', edit_projet_form_path(projet_form) %></td>
        <td><%= link_to 'Destroy', projet_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Projet Form', new_projet_form_path %>

app/views/projet_forms/new.html.erb
<h1>New Projet Form</h1>

<%= render 'form', projet_form: @projet_form %>

<%= link_to 'Back', projet_forms_path %>

app/views/projet_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Projet:</strong>
  <%= @projet_form.projet_id %>
</p>

<p>
  <strong>Form:</strong>
  <%= @projet_form.form_id %>
</p>

<%= link_to 'Edit', edit_projet_form_path(@projet_form) %> |
<%= link_to 'Back', projet_forms_path %>