config/routes.rb
Rails.application.routes.draw do
  resources :projet_themes
  resources :projet_forms
  resources :projet_targets
  resources :projets
  resources :forms
  resources :themes
  resources :targets
  devise_for :users
  get "home", to: "pages#home"
  get "quizz", to: "pages#quizz"
  get "about", to: "pages#about"
  get "mention", to: "pages#mention"
  get "update", to: "pages#update"
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/projet_target.rb
class ProjetTarget < ApplicationRecord
  belongs_to :projet
  belongs_to :target
end

app/controllers/projet_targets_controller.rb
class ProjetTargetsController < ApplicationController
  before_action :set_projet_target, only: [:show, :edit, :update, :destroy]

  # GET /projet_targets
  # GET /projet_targets.json
  def index
    @projet_targets = ProjetTarget.all
  end

  # GET /projet_targets/1
  # GET /projet_targets/1.json
  def show
  end

  # GET /projet_targets/new
  def new
    @projet_target = ProjetTarget.new
  end

  # GET /projet_targets/1/edit
  def edit
  end

  # POST /projet_targets
  # POST /projet_targets.json
  def create
    @projet_target = ProjetTarget.new(projet_target_params)

    respond_to do |format|
      if @projet_target.save
        format.html { redirect_to @projet_target, notice: 'Projet target was successfully created.' }
        format.json { render :show, status: :created, location: @projet_target }
      else
        format.html { render :new }
        format.json { render json: @projet_target.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projet_targets/1
  # PATCH/PUT /projet_targets/1.json
  def update
    respond_to do |format|
      if @projet_target.update(projet_target_params)
        format.html { redirect_to @projet_target, notice: 'Projet target was successfully updated.' }
        format.json { render :show, status: :ok, location: @projet_target }
      else
        format.html { render :edit }
        format.json { render json: @projet_target.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projet_targets/1
  # DELETE /projet_targets/1.json
  def destroy
    @projet_target.destroy
    respond_to do |format|
      format.html { redirect_to projet_targets_url, notice: 'Projet target was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projet_target
      @projet_target = ProjetTarget.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def projet_target_params
      params.require(:projet_target).permit(:projet_id, :target_id)
    end
end

app/views/projet_targets/_form.html.erb
<%= simple_form_for(@projet_target) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :projet %>
    <%= f.association :target %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/projet_targets/edit.html.erb
<h1>Editing Projet Target</h1>

<%= render 'form', projet_target: @projet_target %>

<%= link_to 'Show', @projet_target %> |
<%= link_to 'Back', projet_targets_path %>

app/views/projet_targets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projet Targets</h1>

<table>
  <thead>
    <tr>
      <th>Projet</th>
      <th>Target</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projet_targets.each do |projet_target| %>
      <tr>
        <td><%= projet_target.projet_id %></td>
        <td><%= projet_target.target_id %></td>
        <td><%= link_to 'Show', projet_target %></td>
        <td><%= link_to 'Edit', edit_projet_target_path(projet_target) %></td>
        <td><%= link_to 'Destroy', projet_target, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Projet Target', new_projet_target_path %>

app/views/projet_targets/new.html.erb
<h1>New Projet Target</h1>

<%= render 'form', projet_target: @projet_target %>

<%= link_to 'Back', projet_targets_path %>

app/views/projet_targets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Projet:</strong>
  <%= @projet_target.projet_id %>
</p>

<p>
  <strong>Target:</strong>
  <%= @projet_target.target_id %>
</p>

<%= link_to 'Edit', edit_projet_target_path(@projet_target) %> |
<%= link_to 'Back', projet_targets_path %>